package net.eclipce.transpondersnails.visual.client;

import net.eclipce.transpondersnails.TransponderSnails;
import net.eclipce.transpondersnails.visual.VisualCallConstants;
import net.eclipce.transpondersnails.visual.VisualGlow;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.ModelManager;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.client.event.ModelEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import javax.annotation.Nullable;

/**
 * The "glow" models of the visual snails: their eyes, and the projector part of the Visual Transponder Snail, as small models of their
 * own (generated by tools/generate_glow_models.py from the real snail models). The game draws them full-bright, exactly over the
 * original parts, while those parts are working - that is what makes only the eyes and the projector glow instead of the whole snail.
 *
 * Registered here with the same event the project uses for its other extra models, so no other file needs to know about them.
 */
@Mod.EventBusSubscriber(modid = TransponderSnails.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
@OnlyIn(Dist.CLIENT)
public final class VisualGlowModels {

    private static final String PROJECTOR = VisualCallConstants.DUPLEX_SNAIL_ID;
    private static final String CAMERA = VisualCallConstants.CAMERA_SNAIL_ID;

    /** Model names (assets/transpondersnails/models/block/NAME.json), also used by the renderer through the same helpers. */
    static String eyes(String snail, boolean hasSound, boolean inCall) {
        return snail + "_glow_eyes_" + VisualGlow.modelState(hasSound, inCall);
    }

    static String projector(String snail) {
        return snail + "_glow_projector";
    }

    static String projectorTop(String snail) {
        return snail + "_glow_projector_top";
    }

    static String projectorSnail() { return PROJECTOR; }

    static String cameraSnail() { return CAMERA; }

    private VisualGlowModels() {}

    @SubscribeEvent
    public static void onRegisterAdditional(ModelEvent.RegisterAdditional event) {
        for (boolean hasSound : new boolean[]{false, true}) {
            for (boolean inCall : new boolean[]{false, true}) { // idle, sound, call, active
                event.register(location(eyes(PROJECTOR, hasSound, inCall)));
                event.register(location(eyes(CAMERA, hasSound, inCall)));
            }
        }
        event.register(location(projector(PROJECTOR)));
        event.register(location(projectorTop(PROJECTOR)));
    }

    private static ResourceLocation location(String name) {
        return new ResourceLocation(TransponderSnails.MOD_ID, "block/" + name);
    }

    /** The baked glow model, or null if it is not there (the JSON file is missing): then the part simply does not glow. */
    @Nullable
    static BakedModel get(String name) {
        ModelManager manager = Minecraft.getInstance().getModelManager();
        BakedModel model = manager.getModel(location(name));
        return model == manager.getMissingModel() ? null : model;
    }
}
